### ISSUE TITLE
Top Panel Volume Control progress bar with indicator.

### ISSUE THREAD

**Issue by khandakershahi** [WernerFP/Shades-of-gray-theme#1]
Please see the image. It has indicator but no progress bar.

![shade-gray](https://user-images.githubusercontent.com/36885524/50100768-69107600-024b-11e9-8b69-a8acb1e705fc.png)

For your clarification I had another image of another theme.
![nordic](https://user-images.githubusercontent.com/36885524/50100994-e0460a00-024b-11e9-9f48-364cb2f24aff.png)

If you could do anything about it would be nice.
Thanks.

**Comment by WernerFP** [comment]
Thank you for reporting!
To reproduce it: Which application or extension is shown in your picture?

The progress bar in Gnome panel is visible on my systems…

![gnome_panel_volume_v1 1 3 1](https://user-images.githubusercontent.com/22373662/50106060-eb3e7180-022e-11e9-84e7-86318c383738.jpg)

**Comment by khandakershahi** [comment]
Thank you for reply.
The images I showed you using no extension I just took screenshot of my desktop. First image is your theme and the second theme is nordic theme. I am using Manjaro Linux Gnome Desktop.
Here is gtk3-widget-factory image screenshot below.
![screenshot from 2018-12-18 11-33-59](https://user-images.githubusercontent.com/36885524/50134167-00f87900-02b9-11e9-81c6-da878047eb5e.png)

If you need any other information please ask. Happy to help.

Regards.

**Comment by khandakershahi** [comment]
FYI I first install your theme using AUR. After update the theme I uninstall theme from AUR and download your update version and copy it to .themes folder. 
Here are my system information. See the images.
![screenshot from 2018-12-18 11-38-51](https://user-images.githubusercontent.com/36885524/50134457-3fdafe80-02ba-11e9-9a84-1fb92c0e6d08.png)
another one
![screenshot from 2018-12-18 11-40-05](https://user-images.githubusercontent.com/36885524/50134473-4cf7ed80-02ba-11e9-9451-e8185d5d3fc1.png)

**Comment by WernerFP** [comment]
Starting with gnome-shell 3.29 the construction of CSS class selector ".slider" has been significantly changed. I've committed some modifications which should solve the problem.

You can install the AUR package [gtk-theme-shades-of-gray-git](https://aur.archlinux.org/packages/gtk-theme-shades-of-gray-git) to get the latest changes.

If you want different colors in your GNOME top panel, you can easily change them by adjusting color or opacity of these two files in Inkscape:
```
Shades-of-gray/gnome-shell/assets/panel/panel.svg
Shades-of-gray/gnome-shell/assets/panel/panel-overview.svg
```

**Comment by khandakershahi** [comment]
Ok. I will give it a try and post here the outcome.
