### ISSUE TITLE
Bug with evolution

### ISSUE THREAD

**Issue by RudySixOw** [WernerFP/Shades-of-gray-theme#11]
Hi, 
In evolution the font color is white for link

**Comment by RudySixOw** [comment]
Thanks it's work. I can keep your beautiful theme.

**Comment by WernerFP** [comment]
I have added the workaround ([a999e16](https://github.com/WernerFP/Shades-of-gray-theme/commit/a999e16c1ef971e4d707af1f3133d91db695969f)).
Thank you for reporting!
