### ISSUE TITLE
Notification bar has jagged shadow

### ISSUE THREAD

**Issue by cgvirus** [WernerFP/Shades-of-gray-theme#12]
Hello thanks for this theme!
Everything is working perfectly In Gnome 3.34 but the notification bar has jagged shadows:
![Screenshot from 2019-10-11 06-50-24](https://user-images.githubusercontent.com/22106885/66616759-e569b080-ebf3-11e9-9913-c8b04def8840.jpg)

**Comment by WernerFP** [comment]
Thank you for reporting!

The notification bar was designed with SVG graphics. Starting from Gnome 3.34 this causes apparently unsightly side effects.
I just fixed this issue (commit a520f82). Please reinstall the Git version of Shades-of-gray. The jagged shadow should not occur anymore.

**Comment by cgvirus** [comment]
Thanks! It's fixed now, :)
