### ISSUE TITLE
A KDE Plasma Color Scheme is created

### ISSUE THREAD

**Issue by cgvirus** [WernerFP/Shades-of-gray-theme#13]
Hello Greetings! 
Recently I have switched to KDE and for sure I was missing my go to theme Shades of Gray. Can't really live without it. So I have created a pack of color scheme for KDE Plasma using your color codes and some custom tweaks.

https://store.kde.org/p/1330367/

Just to let you know, if users like me, want this for KDE as well. 

Thanks for this awesome theme. You have saved my eyes.

P.S. You can close this non-issue. :) Cheers.

**Comment by WernerFP** [comment]
Great, I really like the screenshots of your Shades of Gray KDE-Plasma color scheme.

I will install KDE in a virtual machine later this week and take a closer look at it.

**Comment by bubbleguuum** [comment]
Thanks for this Plasma color theme. It complements Shades-of-gray-theme nicely when using mixed GTK and Qt programs.
