### ISSUE TITLE
gtk2 panel.rc typo at line 83

### ISSUE THREAD

**Issue by mason362** [WernerFP/Shades-of-gray-theme#14]
There is an incorrect line with value of '2' in the file at line 83, which shouldn't be present. If launching GUI applications via terminal the following error is presented.

``/usr/share/themes/Shades-of-gray-Arch/gtk-2.0/panel.rc:83: error: unexpected number '2', expected keyword - e.g. `style'``

The superfluous line appears to exist in all colour variants.

Tested on Debian Buster with XFCE desktop, using git clone - commit from Dec-26 7126095

**Comment by WernerFP** [comment]
Thanks a lot for your precise reporting!
I fixed the typo just now.

**Comment by mason362** [comment]
Thanks for such prompt action. Can see fix in place via commit d038650. Issue can be closed.
Thank you for providing such a great theme, and such great support.
