### ISSUE TITLE
Notification text color

### ISSUE THREAD

**Issue by skijsche** [WernerFP/Shades-of-gray-theme#15]
I do not know if it is a bug or it is intended to look like this, but i find it too distracting to believe that it is intended design. Text color of notification poping up and also of notifications in notification area is too dark to be easily readable. I am using gnome 3.28.2 on Pop_Os 18.04.  I will probably find a way to fix this for me in a few minutes but since i really like your theme i just wanted to let you know about this bug (if it is bug).
![Screenshot from 2020-02-01 14-44-49](https://user-images.githubusercontent.com/60545090/73593241-23bc1000-4502-11ea-8216-bbbf6c4ab0b1.png)

**Comment by WernerFP** [comment]
Thanks for reporting and your rating on opendesktop.org!
I have just installed Ubuntu 18.04 LTS with Gnome 3.28.2 in a virtual machine:

![Gnome-3 28 2-notification-text-color](https://user-images.githubusercontent.com/22373662/73613543-12086480-45f7-11ea-8f20-5cad24f34021.jpg)

I cannot reproduce the problem in Gnome 3.28.2…

Is Pop_OS using the original Gnome or a custom fork? Is the appearance in Pop_OS okay if you add this instruction to the `gnome-shell.css` file?
```
.message-title,
.message-content {

	color: #f5f5f5;
}
```
If this solves your issue, I'll check a fix with all Gnome versions.

**Comment by edoardopigaiani** [comment]
> Thanks for reporting and your rating on opendesktop.org!
> I have just installed Ubuntu 18.04 LTS with Gnome 3.28.2 in a virtual machine:
> 
> ![Gnome-3 28 2-notification-text-color](https://user-images.githubusercontent.com/22373662/73613543-12086480-45f7-11ea-8f20-5cad24f34021.jpg)
> 
> I cannot reproduce the problem in Gnome 3.28.2…
> 
> Is Pop_OS using the original Gnome or a custom fork? Is the appearance in Pop_OS okay if you add this instruction to the `gnome-shell.css` file?
> 
> ```
> .message-title,
> .message-content {
> 
> 	color: #f5f5f5;
> }
> ```
> 
> If this solves your issue, I'll check a fix with all Gnome versions.

I was experiencing the same issue on Ubuntu 19.10 and I can confirm that the fix you recommended works. Thanks for the awesome theme!

**Comment by WernerFP** [comment]
Thanks for your report!
I will integrate this fix as one of several outstanding updates within the next days.
