### ISSUE TITLE
XFCE Applets issue

### ISSUE THREAD

**Issue by insaide** [WernerFP/Shades-of-gray-theme#16]
When using XFCE in Xubuntu 18.04, 19.10 and 20.04 Beta, there is an issue affecting some xfce applets.

On a default installation, clicking the "Notifications", "Network" or "Calendar" applets opens them, as expected, and clicking a second time closes them, as expected.
Clicking the "Power Manager" or "Sound Volume" applets opens them, as expected. However, clicking a second time (or 3rd, etc) doesn't close them, as it should. The applets stay open and you have to either:

1. click somewhere on the desktop to close  them
2. click on an empty area of the panel to close them
3. press ESC

Worth nothing that in case 2, clicking on the "Window buttons" or "Application Menu" closes the opened applet, but clicking on the "Notifications", "Network" or "Calendar" applets does not close the opened applet, as was to be expected.

This unexpected behaviour only happens with Shades of Gray theme, both Adwaita, Greybird, Numix or Yaru work fine (the opened applet closes when you click on its icon).

Thanks in advance and congrats on your work on my favorite GTK theme.

**Comment by WernerFP** [comment]
@insaide 
Thank you very much for your report! I have fixed this issue.

**Comment by insaide** [comment]
Downloaded the latest git version and confirm the issue is fixed.

Thank you very very much, keep up the good work.
