### ISSUE TITLE
Gnome Shell themes Gnome Clocks issue

### ISSUE THREAD

**Issue by insaide** [WernerFP/Shades-of-gray-theme#17]
Hi

Using Ubuntu 20.04 (Gnome 3.36) with gnome-session (instead of ubuntu-session) on Xorg, with Gnome Clocks installed.
When using the Shades of gray gnome shell theme (any color variant), the Gnome Clocks "widget" below the calendar is not styled. Comparing with the default gnome shell theme or Yaru, it could be styled like the calendar is. Some screenshots below:

default

![default](https://user-images.githubusercontent.com/30356143/84422913-a02fcf80-ac15-11ea-9a98-094bf4435239.png)

yaru

![yaru](https://user-images.githubusercontent.com/30356143/84422963-b3429f80-ac15-11ea-8033-4b4a1229cad9.png)

shades of gray

![shades](https://user-images.githubusercontent.com/30356143/84422991-bfc6f800-ac15-11ea-86c2-5e23671c9cbf.png)

Thanks for all the work on this theme.

**Comment by WernerFP** [comment]
Thanks for reporting!

**Comment by insaide** [comment]
Thank you for fixing. Cheers
