### ISSUE TITLE
Gnome Shell theme Mint variant issue

### ISSUE THREAD

**Issue by insaide** [WernerFP/Shades-of-gray-theme#18]
Hi

When using the Shades of gray - Mint gnome shell theme, the accent color isn't correctly applied (should use the gtk accent color, as the other theme variants use). Below is a comparison with the Harvest variant:

Menu Shades of gray - Harvest

![menu-harvest](https://user-images.githubusercontent.com/30356143/84424415-fb62c180-ac17-11ea-8f4a-4faa92a1c475.png)

Menu Shades of gray - Mint

![menu-mint](https://user-images.githubusercontent.com/30356143/84424477-12091880-ac18-11ea-80fa-8c4de84c553f.png)

Status Shades of gray - Harvest

![status-harvest](https://user-images.githubusercontent.com/30356143/84424537-251be880-ac18-11ea-86c0-6338cedf6cc6.png)

Status Shades of gray - Mint

![status-mint](https://user-images.githubusercontent.com/30356143/84424567-31a04100-ac18-11ea-9fc8-f41846193e6f.png)

Thanks for all the work on this theme.

**Comment by WernerFP** [comment]
Thank you very much for your reports and suggestions! Your contributions to quality assurance are really helpful.

**Comment by insaide** [comment]
Can confirm the issue is fixed.

Thank you for quick fixing, and providing a great theme. Cheers.
