### ISSUE TITLE
Suggestion: make gnome shell theme follow system font settings

### ISSUE THREAD

**Issue by insaide** [WernerFP/Shades-of-gray-theme#19]
Hi

Would it be possible to make the Shades of gray gnome shell themes follow the system font settings? This was implemented in the default gnome shell theme with the 3.36 version, the shell theme follows the system font style and size.

Thanks in advance

**Comment by WernerFP** [comment]
Thanks for your suggestion!

There are two reasons why I kept the Cantarell font:

1. Version 3.36 only partially respects the users' system font settings. Font size and font weight are statically defined via CSS. Depending on the chosen system font, this can result in a deformed font in Gnome panel.
2. The theme should be compatible with older Gnome versions.

If you don't like Cantarell, please comment out the relevant [line](https://github.com/WernerFP/Shades-of-gray-theme/blob/master/Shades-of-gray/gnome-shell/gnome-shell.css#L120) in your `gnome-shell.css`

**Comment by insaide** [comment]
Editing the relevant line is a nice workaround (I love Fira font). I have to agree with you: indeed, if a badly chosen font can look bad in gnome panel, it's best to just use Cantarell.

Thank you for your response and the tip. Cheers.
