### ISSUE TITLE
Dark on dark color in hexchat

### ISSUE THREAD

**Issue by romildo** [WernerFP/Shades-of-gray-theme#2]
The input area in the hexchat application has a dark foreground on a dark background, making it too hard to read.
![hexchat](https://user-images.githubusercontent.com/1217934/51800652-7bea7300-2219-11e9-96ed-38e2b45ca9ad.png)

**Comment by WernerFP** [comment]
Sorry for the late feedback.
I have implemented a workaround that solves the issue with these entries in Hexchat.

![hexchat-entries](https://user-images.githubusercontent.com/22373662/51994296-bf124380-24b0-11e9-993c-9965abcc66c0.png)

The search entry (CTRL+F) is not affected, it is displayed by Hexchat as it is defined by theme.
*(There are 2 small entries next to 'mode buttons' for which I couldn't find a solution.)*
