### ISSUE TITLE
GNOME Shell theme visual bug

### ISSUE THREAD

**Issue by nd-btw** [WernerFP/Shades-of-gray-theme#20]
![image](https://user-images.githubusercontent.com/57261835/96769747-24a11480-13a5-11eb-9dbd-70995dfe2c65.png)

Other dialogs may also be affected.

**Comment by WernerFP** [comment]
Thank you for reporting!
The problem should now be solved with these commit: 
[Gnome Shell: dialog fixes for 3.38 (gnome-shell.css)](https://github.com/WernerFP/Shades-of-gray-theme/commit/ead6cd755a0a2a1cdf7bdf5efc7e61fe90633772)

**Comment by nd-btw** [comment]
Fix verified working on my end. Thanks!
