### ISSUE TITLE
Unread message titles hard to distinguish in Thunderbird

### ISSUE THREAD

**Issue by bubbleguuum** [WernerFP/Shades-of-gray-theme#3]
Hi,

First, thank you for this magnificent theme. I use it with Eclipse, Firefox and Thunderbird.
For Thunderbird, when using the Shades-of-gray theme + Thunderbird 'app-gadget', the unread message titles in the list pane are hard to distinguish from unread messages. That's because text is white for both with the unread messages just being bold, which makes them are to distinguish. I think coloring them (for example orange) would be better. The same could be apply to the left mailbox pane when a folder has new messages.

**Comment by WernerFP** [comment]
I'm not a friend of colored fonts for marking - apart from special purposes like code highlighting (*by the way: work in progress for Shades of gray*).

If you prefer an orange font color for unread messages, you can easily set this up yourself. Just copy this code snippet to the end of the file `userChrome.css`:
```
#threadTree treechildren::-moz-tree-cell-text(unread),
treechildren::-moz-tree-cell-text(hasUnreadMessages-true) {

	font-weight: bold !important;
	font-style: italic !important;
	color: orange !important;
}
#threadTree treechildren::-moz-tree-cell-text(selected) {

	color: white !important;
}
```

**Comment by bubbleguuum** [comment]
Many thanks ! It's a lot better now.

**Comment by WernerFP** [comment]
You're welcome!
Even as a sceptic of colored fonts, I have to admit it's an improvement.

I've made some adjustments:
```
#threadTree > treechildren::-moz-tree-cell-text(unread),
#folderTree > treechildren::-moz-tree-cell-text(hasUnreadMessages-true) {

	color: var(--tree-link-color) !important;
}
#threadTree > treechildren::-moz-tree-cell-text(selected),
#folderTree > treechildren::-moz-tree-cell-text(selected) {

	color: var(--base_fg_selected) !important;
}
```
So the color is consistent with the color for new messages. Important is that the color of the selected title switches to white font. Otherwise the selected title would not be readable in all colors of Shades of gray.
I'll implement this for the next release.

If you prefer orange you can insert the code snippet again at the end of `userChrome.css` and change the color instruction to `color: orange !important;`. The last instruction overwrites the previous one.

**Comment by bubbleguuum** [comment]
It's just fine with these adjustments. Your dark theme + custom CSS just rocks. It's incredibly readable and easy on the eyes vs other dark themes.

**Comment by SirY4** [comment]
sorry I am a noob. I applied the changes to my chromecss and like it. Can you tell me which line will change the color of new unread messages opposed to later "marked as unread" ?
Thank you very much!

**Comment by WernerFP** [comment]
In the current release 1.2.1 the color of unread messages is defined in [line 706](https://github.com/WernerFP/Shades-of-gray-theme/blob/3b13220416017f0065242dc22623e20e66ef126a/Shades-of-gray/app-gadgets/Thunderbird-Shades-of-gray/userChrome.css#L706) of userChrome.css.
