### ISSUE TITLE
Texts are not visible when downloading files-Chrome

### ISSUE THREAD

**Issue by abimagnus** [WernerFP/Shades-of-gray-theme#4]
First of all thank you for creating this awesome dark theme ! One issue(may be) i found is that text are not visible when downloading files in chrome.Please find the attached image..Other than that all are perfect :) !
![crop](https://user-images.githubusercontent.com/8939183/56229845-7bcf7600-6098-11e9-8675-6a70261f2deb.png)

**Comment by WernerFP** [comment]
Thanks for your positive feedback!

To solve this issue with the download bar, you can force "dark mode" in Chromium or Chrome by setting a flag:

`chromium --force-dark-mode`
or
`google-chrome-stable --force-dark-mode`

**Comment by abimagnus** [comment]
Worked fine..Thank You !
