### ISSUE TITLE
Desktop Icons/Names Misaligned

### ISSUE THREAD

**Issue by phpbbireland** [WernerFP/Shades-of-gray-theme#6]
Testing on MX Linux, Shades-of-gray & Shades-of-gray-Harvest cause Desktop Icons and icon text/names to misalign. Text under icon aligned way left of icon?
https://forum.mxlinux.org/download/file.php?id=14957&mode=view

**Comment by WernerFP** [comment]
That's an Xfce4 problem. The icon text-align is controlled by Xfce4 via xfconf.
Please try this command:

`xfconf-query -c xfce4-desktop -p /desktop-icons/center-text -n -t bool -s false`

_(You can also change this setting in Xfce4 Settings Editor.)_

**Comment by WernerFP** [comment]
I'm assuming the problem's solved.
