### ISSUE TITLE
Transparency issue with Gnome Web UrlBar dropdown

### ISSUE THREAD

**Issue by squalou** [WernerFP/Shades-of-gray-theme#7]
Hi,

I don't know what element is used to paint the 'url bar dropdown' in Gnome Web (formerly Epiphany), but with Shades-of-grey themes I get an unreadable transparent dropdown (see picture attached)

I tried (for less than 5 minutes :) ) to play around css files but ... didn't find it out.

I can patch it on my side if you prefer, just point me (if you can) to the right place to tweak.

![Untitled](https://user-images.githubusercontent.com/4623644/59257311-fe5a5900-8c35-11e9-88c1-4a99ecbc7a88.png)

regards

**Comment by WernerFP** [comment]
Thanks for your report!
Epiphany needs a gtk variable (_content_view_bg_) that I didn't specify.
I just fixed it.

**Comment by squalou** [comment]
Cool, thank you!
