### ISSUE TITLE
Issue with text when using Nautilus

### ISSUE THREAD

**Issue by insaide** [WernerFP/Shades-of-gray-theme#8]
Hi

Using Nautilus to browse a folder populated with long file/folder names looks like this:

![screenshot1](https://user-images.githubusercontent.com/30356143/60931943-938f5280-a2b3-11e9-93de-dcf687d60040.png)

![screenshot2](https://user-images.githubusercontent.com/30356143/60931947-9ab66080-a2b3-11e9-833e-0bfff65c9551.png)

Using Adwaita or Arc theme, for example, will look like this:

![screenshot3](https://user-images.githubusercontent.com/30356143/60931960-b3267b00-a2b3-11e9-9885-8d7e2a1e864a.png)

![screenshot4](https://user-images.githubusercontent.com/30356143/60931964-b6216b80-a2b3-11e9-9323-ad26b175a324.png)

![screenshot5](https://user-images.githubusercontent.com/30356143/60931967-b7eb2f00-a2b3-11e9-85be-77485e29a5ad.png)

![screenshot6](https://user-images.githubusercontent.com/30356143/60931970-b9b4f280-a2b3-11e9-93e7-ef35d3e0dd6a.png)

Maybe the "selected item(s) bottom bar" could have a background color for easier reading?

This theme is amazing, great work and many thanks.

**Comment by WernerFP** [comment]
Thank you for reporting!
I just fixed this issue. Please reinstall the Git version or add these lines in `~/.config/gtk-3.0/gtk.css` until the next release:
```
.nautilus-window .floating-bar {
	background-color: #3a3a3a;
	border: 1px solid #3a3a3a;
}
```

**Comment by insaide** [comment]
Reinstalled the git version, as suggested, and issue is fixed.

Thank you, keep up the good work.
